<?php
return [
  'settings' => [
    'site_name' => '极简论坛',
    'slogan' => '功能简单,界面简洁,移动优先',
    'description' => 'Simple Forum,极简论坛',
    'icp' => '',
    'admin_email' => '',
    'offline' => 0,
    'offline_msg' => '网站维护中，请稍后访问..',
    'access_auth' => 0,
    'email_verify' => 0,
    'admin_verify' => 0,
    'close_register' => 0,
    'username_filter' => '',
    'captcha_enabled' => 0,
    'head_meta' => '',
    'analytics_code' => '',
    'timezone' => 'Asia/Shanghai',
    'footer_links' => [
    ],
    'editor' => 'wysibb',
    'cache_enabled' => 0,
    'cache_time' => 10,
    'auth_enabled' => 0,
    'qq_appid' => '',
    'qq_appkey' => '',
    'qq_scope' => 'get_user_info',
    'wb_key' => '',
    'wb_secret' => '',
    'index_pagesize' => 20,
    'list_pagesize' => 20,
    'comment_pagesize' => 20,
    'hot_topic_num' => 10,
    'hot_node_num' => 20,
    'edit_space' => 30,
    'mailer_host' => '',
    'mailer_port' => 0,
    'mailer_encryption' => '',
    'mailer_username' => '',
    'mailer_password' => '',
  ]
];
